name: Pigeon
description: Labs EnX
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  # VersÃµes
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  sqflite: ^2.3.0
  path: ^1.9.1
  archive: ^4.0.7
  image: ^4.7.2
  json_annotation: ^4.9.0
  crypto: ^3.0.7
  xml: ^6.5.0
  yaml: ^3.1.3
  vector_math: ^2.1.4
  audioplayers: ^5.2.1
  vibration: ^2.0.1
  device_info_plus: ^11.3.0
  path_provider: ^2.0.5
  uuid: ^4.5.2
  qr_code_scanner_plus: ^2.0.14
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  lints: ^3.0.0
  pigeon: ^21.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png" 
  adaptive_icon_background: "#0A0E19" 
  adaptive_icon_foreground: "assets/images/logo.png"
  